name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run a one-line script
      run: echo Hello, world!

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: 
      name: production
      url: ${{ steps.deploy.outputs.url }}
    
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2.4.1

    - name: npm install and build
      run: |
        npm ci
        npm run build

    - name: 'Deploy to production'
      id: deploy
      run: echo "Deploying to production server"
