name: GitHub Actions Demo
on: [push]
env:
  message: hi

jobs:
  job0:
    name: $message
    runs-on: ubuntu-latest
    env:
      message: bye
    steps:
      - run: echo $message
  job1:
    needs: job0
    runs-on: ubuntu-latest
    steps:
      - run: echo $message
