name: GitHub Actions Demo
on: [push]

jobs:
  job1:
    outputs:
      o1: ${{steps.set.outputs.a}}
    runs-on: ubuntu-latest
    steps:
      - id: set
        run: echo "a=1" >> $GITHUB_OUTPUT
      - run: echo ${{steps.set.outputs.a}}
  job2:
    runs-on: ubuntu-latest
    steps:
      - id: set2
        run: echo "a=1" >> $GITHUB_OUTPUT
      - run: echo ${{needs.job1.outputs.o1}}


