name: Auto and Manual Workflow

on:
  push:
    branches:
      - main

jobs:
  auto_job:
    name: Auto Job
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Run Auto Job
      run: |
        echo "Running Auto Job"
        # Add your auto job commands here

  manual_job:
    name: Manual Job
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_run' && github.event.workflow_run.event == 'workflow_run' && github.event.workflow_run.conclusion == 'success'

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Wait for User Approval
      run: |
        echo "Waiting for user approval"
        # Add your approval logic here
