name: GitHub Actions Demo
on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 3
      - run: date
  job2:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 3
      - run: date
