name: GitHub Actions Demo
on: 
  - workflow_dispatch
  - push  

jobs:
  job1:
    outputs:
      o1: ${{steps.set.outputs.a}}
      o2: hi
    runs-on: ubuntu-latest
    steps:
      - id: set
        run: echo "a=1" >> $GITHUB_OUTPUT
      - run: echo ${{steps.set.outputs.a}}
      - run: echo ${{steps.set.outcome}}
      - run: echo ${{steps.set.conclusion}}
  job2:
    environment: production
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{needs.job1.outputs.o1}}
      - run: echo ${{needs.job1.outputs.o2}}
      - run: echo ${{needs.job1.result}}


