name: Phonebook Backend
on: [deployment, workflow_dispatch]

jobs:
  ci:
    outputs:
      o1: ${{steps.test.outputs.a}}
      o2: hi
    runs-on: ubuntu-latest
    steps:
      - id: test
        run: echo "a=1" >> $GITHUB_OUTPUT
      - run: echo ${{steps.test.outputs.a}}
  deploy-qa:
    environment: qa
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - run: |
          echo ${{needs.ci.outputs.o1}}
          sleep 2
      - run: sleep 3
      - run: sleep 3
      - run: sleep 3
      - run: sleep 3
      - run: sleep 3
      - run: sleep 3
      - run: sleep 3
  deploy-prod:
    environment: production
    runs-on: ubuntu-latest
    needs: deploy-qa
    steps:
      - run: sleep 2
      - run: echo "deploy to prod"


