name: My workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the project
        run: echo "Building the project..."

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get user approval
        uses: actions/github-script@v3
        with:
          script: |
            const approval = await github.actions.getSecret('DEPLOY_APPROVAL');
            if (!approval) {
              throw new Error('Please approve the deployment before continuing.');
            }

      - name: Deploy the project
        run: echo "Deploying the project..."
