name: GitHub Actions Demo
on: [push]
env:
  message: hi

jobs:
  job0:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 3
      - run: echo $message
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 3
      - run: date


