name: Phonebook Backend
on: 
  - workflow_dispatch
  - push  

jobs:
  ci:
    outputs:
      o1: ${{steps.test.outputs.a}}
      o2: hi
    runs-on: ubuntu-latest
    steps:
      - id: test
        run: echo "a=1" >> $GITHUB_OUTPUT
      - run: echo ${{steps.test.outputs.a}}
      - run: echo ${{steps.test.outcome}}
      - run: echo ${{steps.test.conclusion}}
  deploy-qa:
    environment: qa
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - run: echo ${{needs.ci.outputs.o1}}
      - run: echo ${{needs.ci.outputs.o2}}
      - run: echo ${{needs.ci.result}}
  deploy-prod:
    environment: production
    runs-on: ubuntu-latest
    needs: deploy-qa
    steps:
      - run: sleep 3
      - run: deply to prod


