name: Manual Workflow

on:
  workflow_dispatch:
    inputs:
      environmentx:
        description: 'Environment to deploy'
        required: true
        default: 'staging'
        
    

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Deploy to Environment
      run: |
        echo "Deploying to ${{ github.event.inputs.environmentx }} environment"
        # Add your deployment commands here
