name: GitHub Actions Demo
on: [push]
env:
  message: hi

jobs:
  job0:
    name: my job
    runs-on: ubuntu-latest
    env:
      message: bye
    steps:
      - run: echo $message
        env:
          message: step1
      - run: echo $message
  job1:
    needs: job0
    runs-on: ubuntu-latest
    steps:
      - run: echo $message
